### ISSUE TITLE
[REQUEST] Deno Support

### ISSUE THREAD

**Issue by btd1337** [tonysamperi/ts-luxon#10]
Hi @tonysamperi,

Firstly, congratulations on this great work; ts-luxon is truly amazing.

I feel that a date library like ts-luxon is missing in the Deno ecosystem. It would be great if you could consider sharing your library on [Deno Land](https://deno.land/x).

Deno + TS-Luxon is the perfect combination, and you could make this possible.

Thanks in advance!

**Comment by tonysamperi** [comment]
Hi @btd1337 

Done, but I don't know if it'll ever get updates, cause it says to create tags from the repo to push updates.
I only tag the releases from git.

**Comment by btd1337** [comment]
@tonysamperi Where's the link to your library on the Deno Land? Is It already published?

**Comment by tonysamperi** [comment]
@btd1337 tsluxon

**Comment by btd1337** [comment]
@tonysamperi I really don't see your library in Deno Land. Can you share the link with me?

Another thing, I think it would be interesting to maintain consistency with the library name, following the pattern of other libraries: **ts_luxon**

<img width="953" alt="Captura de Tela 2024-01-28 às 18 19 56" src="https://github.com/tonysamperi/ts-luxon/assets/11943860/3b341c1b-e408-4d51-94d1-f76ae299d3cd">

---

<img width="944" alt="Captura de Tela 2024-01-28 às 18 25 52" src="https://github.com/tonysamperi/ts-luxon/assets/11943860/dda1102c-b180-4a36-9629-b3214f94cdb7">

---

<img width="953" alt="Captura de Tela 2024-01-28 às 18 20 11" src="https://github.com/tonysamperi/ts-luxon/assets/11943860/544d3cd4-b00d-46c6-ac67-3812d2fac99c">

---

<img width="954" alt="Captura de Tela 2024-01-28 às 18 20 23" src="https://github.com/tonysamperi/ts-luxon/assets/11943860/eed5e3d8-7fb4-43c8-b149-9cb7741c0151">

**Comment by tonysamperi** [comment]
I created it and set the webhook.
For the name, since I couldn't insert the dash and noticed they were all lowercase I opted for the umd name in lowercase, which is tsLuxon, hence tsluxon.
I'll check what happened on deno because I couldn't find the link either...
And I would expect it to be https://deno.land/x/tsluxon
I'll let you know in the next few days...
Cheers

**Comment by tonysamperi** [comment]
Hi @btd1337 sorry it took a while...hard times...
It needed at least a tag to trigger the webhook...
I tagged v 4.5.2, now the link above works!

**Comment by RawmanGrey** [comment]
May be I'm doing something wrong, but when trying import as below
`import * as tsluxon from "https://deno.land/x/tsluxon@4.5.2/src/index.ts";`
error `Module not found "https://deno.land/x/tsluxon@4.5.2/src/datetime"` occures

Apparently, it fails to resolve "./datetime" as datetime.ts in index.ts

**Comment by btd1337** [comment]
@tonysamperi the way that handles exports is still not working.

How to reproduce:

```ts
// test.ts
import * as tsluxon from "https://deno.land/x/tsluxon@4.5.2/src/index.ts"

console.log(tsluxon);
```

```
deno run test.ts
```

```
error: Module not found "https://deno.land/x/tsluxon@4.5.2/src/datetime".
    at https://deno.land/x/tsluxon@4.5.2/src/index.ts:1:26
```
