### ISSUE TITLE
Incorrect NPM link on doc site

### ISSUE THREAD

**Issue by MatthewCushing** [tonysamperi/ts-luxon#3]
**Describe the bug**
Doc site shows `npm install --save luxon` when it should be `npm install --save ts-luxon`

I'd put in a PR myself but I couldn't find where the docs were located here or in your portfolio repo (repo looks to be bundled for prod prior to push unlike the `old/` directory of your previous portfolio).

Just had to add that I really appreciate your TypeScript conversion of the repo since the DefinitelyTyped `@types/luxon` does not contain the complete types (ex. properties on the DateTime object).

**Comment by tonysamperi** [comment]
@MatthewCushing 
Yeah I had to organize the docs differently...I put them in an Angular app...way cooler this way IMHO!
Thanks for reporting!
