### ISSUE TITLE
Missing files warning in build

### ISSUE THREAD

**Issue by Holecek-M** [tonysamperi/ts-luxon#5]
**Describe the bug**
There are missing files errors in the build log.
```
WARNING in ../node_modules/ts-luxon/dist/ts-luxon.es6.js
Module Warning (from ../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'node_modules/src/zones/fixedOffsetZone.ts' file: Error: ENOENT: no such file or directory, open...
```

**To Reproduce**
Build the project with newest ts-luxon@4.2.2

**Actual vs Expected behavior**
Build without warnings and errors.

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Crome
- Luxon version 4.2.2

**Additional context**
It was not there before the bugfix. I am doing weekly updates.

**Comment by Holecek-M** [comment]
The full list of missing files is:
src/datetime.ts
src/duration.ts
src/errors.ts
impl/conversions.ts
impl/diff.ts
impl/digits.ts
impl/english.ts
impl/formats.ts
impl/formatter.ts
impl/locale.ts
impl/regexParser.ts
impl/tokenParser.ts
impl/util.ts
impl/zoneUtil.ts
src/index.ts
src/info.ts
src/interval.ts
src/settings.ts
types/intl-next.ts
types/invalid.ts
src/zone.ts
zones/IANAZone.ts
zones/fixedOffsetZone.ts
zones/invalidZone.ts
zones/systemZone.ts

**Comment by tonysamperi** [comment]
Do you think I would have published if I had such warnings?
Look at the actions, no warning. 
There must be something on your side!

**Comment by SeamusY** [comment]
@tonysamperi I ran into something similar, for 4.4.0 causes no blocking issues but curious any idea why it mentions this? even though i checked the node_modules and i see the file does exist... any idea?

my issue:

`Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map`

**Comment by tonysamperi** [comment]
@SeamusY the point is...can any of you create a blitz reproducing the issue?
