### ISSUE TITLE
Wrong path to typings in 4.3.0 package.json

### ISSUE THREAD

**Issue by jppresents** [tonysamperi/ts-luxon#6]
In the package json it says:

    "typings": "dist/index.d.ts",

but in 4.3.0 the actual index.d.ts has been moved to here:

"dist/lib/index.d.ts"

Without adjusting the package.json information.

This leads to the following error in our builds: error TS7016: Could not find a declaration file for module 'ts-luxon'

**Comment by tonysamperi** [comment]
mmm very wierd...fixing right away!

**Comment by tonysamperi** [comment]
ok it's not wrong the path in the index, but it's wrong the output path...
Just figuring out why it changed, I don't remember editing the tsconfig...
Maybe the version of rollup typescript? 🤔

**Comment by tonysamperi** [comment]
@jppresents yes. What I meant was that the path shouldn't have changed, so it's a build problem and not a package.json problem :)
Anyway fixed in 4.3.1

**Comment by tonysamperi** [comment]
Fixed in v 4.3.2!
