### ISSUE TITLE
Defined return types do not match implementation

### ISSUE THREAD

**Issue by kurt-west** [tonysamperi/ts-luxon#8]
**Describe the bug**
There are numerous places where return type defined in method signature does not match the actual return type.

An example is toJson(), the method signature returns a string; however, the implementation directly returns .toISO() which returns a string | null

**Additional context**
With nearly every property having null (or Nan in the case of numbers) return type option the use of this library in a project with strict: true is painful as every property needs to be non-null asserted - gross - or if guarded to keep TS happy. 

Personally, I think a more TS friendly approach would be properties/methods return the expected type of a valid object, or throw an error in the case of invalid objects. It would then be the callers responsibility to validate the object prior to use, by either checking isValid() or enabling throwOnInvalid.

**Comment by tonysamperi** [comment]
Man this is not the way of creating an issue.

1. "Numerous places". Then you only report 1.
2. I can't change the implementations (e.g. throwing on invalid). They need to be coherent with the original Luxon. There are a few things I changed (for the better I hope), but it's small things. The "Invalid" state of luxon is handled with null returns.
3. Yes I guess we could remove the `| null` where it can return `null` when invalid.

I'll check the `toJson` method.

**Comment by tonysamperi** [comment]
v 4.5.1
Removed the latest null return types I added

**Comment by kurt-west** [comment]
> Man this is not the way of creating an issue.
> 
> 1. "Numerous places". Then you only report 1.
> 2. I can't change the implementations (e.g. throwing on invalid). They need to be coherent with the original Luxon. There are a few things I changed (for the better I hope), but it's small things. The "Invalid" state of luxon is handled with null returns.
> 3. Yes I guess we could remove the `| null` where it can return `null` when invalid.
> 
> I'll check the `toJson` method.

@tonysamperi - I'm sorry the wording, maybe, multiple would have been a better choice of words. 

As far are examples, you are correct, I provided a single example; however, I felt the a simple single example would highlight the underlying issue and didn't feel highlighting every method that was incorrectly typed would bring value to the topic. I now understand you do see value in that, so in the future I will be sure to do so.

**Comment by tonysamperi** [comment]
> > Man this is not the way of creating an issue.
> > 
> > 1. "Numerous places". Then you only report 1.
> > 2. I can't change the implementations (e.g. throwing on invalid). They need to be coherent with the original Luxon. There are a few things I changed (for the better I hope), but it's small things. The "Invalid" state of luxon is handled with null returns.
> > 3. Yes I guess we could remove the `| null` where it can return `null` when invalid.
> > 
> > I'll check the `toJson` method.
> 
> @tonysamperi - I'm sorry the wording, maybe, multiple would have been a better choice of words.
> 
> As far are examples, you are correct, I provided a single example; however, I felt the a simple single example would highlight the underlying issue and didn't feel highlighting every method that was incorrectly typed would bring value to the topic. I now understand you do see value in that, so in the future I will be sure to do so.

Yes, now you're talking! If you have concrete examples of bad typings let me now and I'll check.

Cheers
