### ISSUE TITLE
Documentation update | nullOnInvalid

### ISSUE THREAD

**Issue by kurt-west** [tonysamperi/ts-luxon#9]
**Describe the issue**
The documentation of some methods - listed below - does not match the implementation. The documentation lists one can pass  `@param {boolean} [options.nullOnInvalid=false] - return null on invalid values instead of throwing an error`; however, this property does not exist on the type of `DateTimeOptions` which is used to type the `[options|opts]` parameter used in most `DateTime` class methods.

**Instances of [options|opts].nullOnInvalid being referenced**
 - [DateTime.diff()](https://github.com/tonysamperi/ts-luxon/blob/fe666d77124efb1d0b8d7c481ee618ef93542251/src/datetime.ts#L1506)
 - [DateTime.fromSeconds()](https://github.com/tonysamperi/ts-luxon/blob/fe666d77124efb1d0b8d7c481ee618ef93542251/src/datetime.ts#L1143)
 - [DateTime.fromJSDate()](https://github.com/tonysamperi/ts-luxon/blob/fe666d77124efb1d0b8d7c481ee618ef93542251/src/datetime.ts#L937)
 - [DateTime.fromMillis()](https://github.com/tonysamperi/ts-luxon/blob/fe666d77124efb1d0b8d7c481ee618ef93542251/src/datetime.ts#L965)

**Comment by tonysamperi** [comment]
Fixed in 4.5.2
